# GET DATA ADMIN IN SESSION
GET http://localhost:8000/api/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDI0NWQxNDQ2MzE4MTllNzEyMTk0MyIsImlhdCI6MTYzMTc4MjUwM30.zL0mSstUc7YV5vOfDWvXKKdWEN0wlYgRwBov6SqFg-0

#
### GET TOKEN IN SESSION
GET http://localhost:8000/api/admin/session
Content-Type: application/json

###
# ADMIN LOGIN
POST http://localhost:8000/api/admin/login
Content-Type: application/json

{
  "nameOrEmail": "febriadji",
  "password": "febri"
}
