# DISPLAY ALL ARTICLES

GET http://localhost:8000/api/articles
Content-Type: application/json

###
# CREATE ARTICLE

POST http://localhost:8000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDI0NWQxNDQ2MzE4MTllNzEyMTk0MyIsImlhdCI6MTYzMTc4MjUwM30.zL0mSstUc7YV5vOfDWvXKKdWEN0wlYgRwBov6SqFg-0
Content-Type: multipart/form-data; boundary=----myBoundary

------myBoundary
Content-Disposition: form-data; name="title"
Content-Type: text/plain

Belajar React Dan Graphql
------myBoundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

Lorem ipsum dolor sit amet
------myBoundary
Content-Disposition: form-data; name="tags"
Content-Type: text/plain

graphql Apollo-server
------myBoundary
Content-Disposition: form-data; name="fileContent"; filename="content.md"
Content-Type: text/markdown

./content.md
------myBoundary--

###
# DELETE ARTICLE

DELETE http://localhost:8000/api/articles?delete=
Content-Type: application/json
